### ISSUE TITLE
求助！

### ISSUE THREAD

**Issue by BetLijeans** [biubiubiiu/L3FNet#1]
您好，我是来自东华大学的大四学生，现在急用该数据集做实验，但是现在数据集原网站进不去了，如果您还存有数据集，请问您能分享一下吗？万分感谢！

**Comment by biubiubiiu** [comment]
> 您好，我是来自东华大学的大四学生，现在急用该数据集做实验，但是现在数据集原网站进不去了，如果您还存有数据集，请问您能分享一下吗？万分感谢！

你好，我把数据集传到网盘了，你可以从这个链接下载：https://mega.nz/file/YE8x0brL#VD__8PkyYBXUWZhvoZsMKPRP1M7836iV2RgImtAfuVI

**Comment by BetLijeans** [comment]
万分感激！



---原始邮件---
发件人: "Raymond ***@***.***&gt;
发送时间: 2024年4月30日(周二) 中午12:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [biubiubiiu/L3FNet] 求助！ (Issue #1)




  
您好，我是来自东华大学的大四学生，现在急用该数据集做实验，但是现在数据集原网站进不去了，如果您还存有数据集，请问您能分享一下吗？万分感谢！
  
你好，我把数据集传到网盘了，你可以从这个链接下载：https://mega.nz/file/YE8x0brL#VD__8PkyYBXUWZhvoZsMKPRP1M7836iV2RgImtAfuVI
