### ISSUE TITLE
L3F datasets

### ISSUE THREAD

**Issue by 2000Zzw** [biubiubiiu/L3FNet#2]
作者您好，L3F数据集的下载网页没有了，请问可以麻烦提供一下这个数据集吗，万分感谢。

**Comment by biubiubiiu** [comment]
> 作者您好，L3F数据集的下载网页没有了，请问可以麻烦提供一下这个数据集吗，万分感谢。

在这里 https://github.com/biubiubiiu/L3FNet/issues/1

**Comment by 2000Zzw** [comment]
> > 作者您好，L3F数据集的下载网页没有了，请问可以麻烦提供一下这个数据集吗，万分感谢。
> 
> 在这里 #1

感谢！
