### ISSUE TITLE
L3Fnet

### ISSUE THREAD

**Issue by 2000Zzw** [biubiubiiu/L3FNet#3]
作者您好，抱歉又在您百忙之中打扰您。
请问代码中有无文中所提到的“直方图模块”，我在提供代码中没有看到；
还有在上次所提供的数据集中，没有文中所提到的L3F-wild;
希望能在有空的时候回复，万分感谢

**Comment by biubiubiiu** [comment]
> 作者您好，抱歉又在您百忙之中打扰您。 请问代码中有无文中所提到的“直方图模块”，我在提供代码中没有看到； 还有在上次所提供的数据集中，没有文中所提到的L3F-wild; 希望能在有空的时候回复，万分感谢

您好，
1. 这份代码中没有实现「直方图模块」。或许您可以参考 https://github.com/CV-IP/LLPackNet/blob/master/ablations/LLPackNet.ipynb 中的实现。这是 L3F-Net 作者的另一篇文章，其中出现了类似的「直方图模块」设计，您可以尝试一下。
2. 抱歉，L3F-wild 数据集我这边没有备份，您可能需要向 L3F-Net 的原作者获取。

**Comment by 2000Zzw** [comment]
感谢感谢！
